insert into utilisateur(pseudo,mdp, admin,adresse,adressemail,nom,prenom) values ('sacha','sacha',true,'56 rue du moulineau','hotmail@gmail.com','sacha','sacha');
insert into utilisateur(pseudo,mdp,admin,adresse,adressemail,nom,prenom) values ('sully','sully',false,'56 rue du sable','gmail@gmail.com','sully','sully');
insert into article(nom,prix,description,categorie,image) values ('brosse metalique','45','petite brosse pour chat en bois naturel','accessoire','/images/articles/brosse.jpg');
insert into article(nom,prix,description,categorie,image) values ('croquette purizon','20','croquette pour chat','croquette','/images/articles/croquette.jpg');
insert into article(nom,prix,description,categorie,image) values ('litiere cat best','10','litiere de qualite cat best original','croquette','/images/articles/litiere.jpg');
insert into article(nom,prix,description,categorie,image) values ('patee purina gourmet','17','patee purina emicee en sauce','croquette','/images/articles/patee.jpg');
insert into commande(idutilisateur,datecommande,adressemail,adresse,nom,prenom) values ('1','2008-10-29','mail@mail.com','77 rue du du','toto','toto');
insert into commande(idutilisateur,datecommande,adressemail,adresse,nom,prenom) values ('1','2008-10-29','mail@mail.com','77 rue du du','toto','toto');
insert into commande(idutilisateur,datecommande,adressemail,adresse,nom,prenom) values ('1','2008-10-29','mail@mail.com','77 rue du du','toto','toto');
insert into commande(idutilisateur,datecommande,adressemail,adresse,nom,prenom) values ('1','2008-10-29','mail@mail.com','77 rue du du','toto','toto');
insert into commande(idutilisateur,datecommande,adressemail,adresse,nom,prenom) values ('2','2008-10-29','mail@mail.com','77 rue du du','toto','toto');
insert into abonnement(idutilisateur, idarticle, age, nom) values ('1', '1', '5', 'mistigri');
insert into note(idarticle,nbnote,notetotale) values (1,10,50);