DROP TABLE IF EXISTS article CASCADE;
DROP TABLE IF EXISTS note CASCADE;
DROP TABLE IF EXISTS utilisateur CASCADE;
DROP TABLE IF EXISTS commande CASCADE;
DROP TABLE IF EXISTS abonnement CASCADE;
CREATE TABLE article(idarticle serial NOT NULL PRIMARY KEY,nom char(20), prix integer, description CHAR(250), image char(100), categorie char(20));
CREATE TABLE utilisateur(idutilisateur serial NOT NULL PRIMARY KEY ,pseudo char(60), mdp char(60),sel char(5), prenom char(20), nom char(30), adresse char(60), adressemail char(70), abonne boolean);
CREATE TABLE commande(idcommande serial NOT NULL PRIMARY KEY, idutilisateur integer, prix integer, datecommande DATE , adresseMail char(70), adresse char(60), nom char(20), prenom char(20), FOREIGN KEY  (idutilisateur) REFERENCES utilisateur(idutilisateur) ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE abonnement(idabonnement serial NOT NULL PRIMARY KEY, idutilisateur integer, idarticle integer, typeabonne char(60) , FOREIGN  KEY (idutilisateur) REFERENCES utilisateur(idutilisateur), FOREIGN KEY (idarticle) REFERENCES article(idArticle) ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE note(idnote serial NOT NULL PRIMARY KEY , idarticle integer NOT NULL, notetotale integer, nbnote integer, FOREIGN KEY (idarticle) REFERENCES article(idarticle) ON DELETE CASCADE ON UPDATE CASCADE);
insert into utilisateur(pseudo,mdp) values ('sacha','sacha');
insert into utilisateur(pseudo,mdp) values ('sully','sully');
insert into article(nom,prix,description,categorie,image) values ('toto','42','c bleu mdr','croquette','/images/Adventure_Time_with_Finn_Jake.png');
insert into article(nom,prix,description,categorie,image) values ('cinamonebun','720','c rouge mdr','litière','/images/Adventure_Time_with_Finn_Jake.png');
insert into commande(idutilisateur,prix,datecommande,adressemail,adresse,nom,prenom) values ('1','20',' 	2008-10-29' ,'mail@mail.com','77 rue du du','toto','toto');
insert into abonnement(idutilisateur, idarticle, typeabonne) values ('1', '1', 'sdfsdfsaag');
insert into note(idarticle,nbnote,notetotale) values (1,10,50);