DROP TABLE IF EXISTS article CASCADE;
DROP TABLE IF EXISTS note CASCADE;
DROP TABLE IF EXISTS utilisateur CASCADE;
DROP TABLE IF EXISTS commande CASCADE;
DROP TABLE IF EXISTS abonnement CASCADE;
DROP TABLE IF EXISTS bonreduction CASCADE;
CREATE TABLE article(idarticle serial NOT NULL PRIMARY KEY,nom char(20), prix integer, description CHAR(250), image char(100), categorie char(20));
CREATE TABLE utilisateur(idUtilisateur serial NOT NULL PRIMARY KEY ,pseudo char(60)  ,mdp char(60),sel char(5), prenom char(20), nom char(30), adresse char(60), adressemail char(70), abonne boolean, admin boolean);
CREATE TABLE commande(idcommande serial NOT NULL PRIMARY KEY, idUtilisateur integer,idarticle integer, datecommande DATE , adresseMail char(70), adresse char(60), nom char(20), prenom char(20), FOREIGN KEY  (idUtilisateur) REFERENCES utilisateur(idUtilisateur),FOREIGN  KEY (idarticle) REFERENCES article(idarticle) ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE abonnement(idabonnement serial NOT NULL PRIMARY KEY, idutilisateur integer, idarticle integer, age integer, poil char(20), sterilise boolean, poids integer, nom char(20), choix integer, FOREIGN  KEY (idutilisateur) REFERENCES utilisateur(idutilisateur) ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE note(idnote serial NOT NULL PRIMARY KEY , idarticle integer NOT NULL, notetotale integer, nbnote integer, FOREIGN KEY (idarticle) REFERENCES article(idarticle) ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE bonreduction(idbonreduction serial NOT NULL PRIMARY KEY , code integer, pourcentage integer, categorie char(20));
insert into utilisateur(pseudo,mdp, admin,adresse,adressemail,nom,prenom) values ('sacha','sacha',true,'56 rue du moulineau','hotmail@gmail.com','sacha','sacha');
insert into utilisateur(pseudo,mdp,admin,adresse,adressemail,nom,prenom) values ('sully','sully',false,'56 rue du sable','gmail@gmail.com','sully','sully');
insert into article(nom,prix,description,categorie,image) values ('brosse metalique','45','petite brosse pour chat en bois naturel','accessoire','/images/articles/brosse.jpg');
insert into article(nom,prix,description,categorie,image) values ('croquette purizon','20','croquette pour chat','croquette','/images/articles/croquette.jpg');
insert into article(nom,prix,description,categorie,image) values ('litiere cat best','10','litiere de qualite cat best original','litiere','/images/articles/litiere.jpg');
insert into article(nom,prix,description,categorie,image) values ('patee purina gourmet','17','patee purina emicee en sauce','patee','/images/articles/patee.jpg');
insert into article(nom,prix,description,categorie,image) values ('croquette chat bio','25','croquette pour chat bio de Equilibre & Instinct gout volaille','croquette','/images/articles/croquette-chat-bio-equilibre-&-instinct-volaille.jpg.png');
insert into article(nom,prix,description,categorie,image) values ('yarrah croquette bio','30','croquette pour chat bio de Yarrah au saumon','croquette','/images/articles/yarrah-croquettes-bio-chat-poisson-800g.jpg');
insert into article(nom,prix,description,categorie,image) values ('litiere chat bio ','15','litiere biologique Plumes et Poils de 10kg','litiere','/images/articles/litiere-biologique-plumes-et-poils.jpg');
insert into article(nom,prix,description,categorie,image) values ('litiere chat bio ','20','litiere biologique Yarrah de 7kg','litiere','/images/articles/litiere-chat-bio-7kg-yarrah.png');
insert into article(nom,prix,description,categorie,image) values ('patee bio saumon','30','patee Yarrah alu au saumon * 20','patee','/images/articles/YARRAH_ALU_CAT_PATE_SALMON_BIO.png');
insert into article(nom,prix,description,categorie,image) values ('patee bio volaille','50','patee Equilibre et Instinct gout volaille * 50','patee','/images/articles/Equilibre_et_instinct_patee_bio_volaille.jpg');
insert into commande(idutilisateur,idarticle,datecommande,adressemail,adresse,nom,prenom) values ('1','1',' 	2008-10-29' ,'mail@mail.com','77 rue du du','toto','toto');
insert into abonnement(idutilisateur, idarticle, age, nom) values ('1', '1', '5', 'mistigri');
insert into note(idarticle,nbnote,notetotale) values (1,10,50);